language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-backbone-keel' ]; then cd .. && eval "mv $currentfolder generator-backbone-keel" && cd generator-backbone-keel; fi

